### ISSUE TITLE
Exponential pacer does not start from min

### ISSUE THREAD

**Issue by technicianted** [technicianted/straggler#2]
Current implementation of exponential pacer steps from started pods non-inclusive. For example:
```yaml
    exponential:
      minInitial: 4
      maxStagger: 16
      multiplier: 4
```
will stagger as follows: 4 -> 8 -> 16.

However it is more intuitive and more efficient to be inclusive: 4 -> 12 -> 24. This way step 1 will use the `multiplier` as well.
